In [64]:
import pandas as pd
import numpy as np

In [65]:
df=pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [66]:
df1=df[['Age','Fare']]
df1.head()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [67]:
from sklearn.impute import SimpleImputer
df1['Age_99']=df1['Age']
df1['Fare_99']=df1['Fare']
df1['Age_minus']=df1['Age']
df1['Fare_minus']=df1['Fare']

C:\Users\ARPIT\AppData\Local\Temp\ipykernel_14428\2363481374.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Age_99']=df1['Age']
C:\Users\ARPIT\AppData\Local\Temp\ipykernel_14428\2363481374.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Fare_99']=df1['Fare']
C:\Users\ARPIT\AppData\Local\Temp\ipykernel_14428\2363481374.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Age_minus']=df1['Age']
C:\Users\ARPIT\AppData\Local\Temp\ipykernel_14428\2363481374.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Fare_minus']=df1['Fare']

In [68]:
df1.head()

    Age     Fare  Age_99  Fare_99  Age_minus  Fare_minus
0  22.0   7.2500    22.0   7.2500       22.0      7.2500
1  38.0  71.2833    38.0  71.2833       38.0     71.2833
2  26.0   7.9250    26.0   7.9250       26.0      7.9250
3  35.0  53.1000    35.0  53.1000       35.0     53.1000
4  35.0   8.0500    35.0   8.0500       35.0      8.0500

In [69]:
imputer1=SimpleImputer(strategy='constant',fill_value=99)
imputer2=SimpleImputer(strategy='constant',fill_value=-1)
columns=df1.columns

In [70]:
from sklearn.compose import ColumnTransformer
trf=ColumnTransformer(transformers=[
    ('99',imputer1,['Age_99','Fare_99']),
    ('-1',imputer2,['Age_minus','Fare_minus'])
],remainder='passthrough')

In [71]:
new_columns = ['Age_99', 'Fare_99', 'Age_minus', 'Fare_minus', 'Age', 'Fare']
df1=trf.fit_transform(df1)

In [72]:
df1=pd.DataFrame(df1,columns=new_columns)

In [73]:
df1.isnull().sum()

Age_99          0
Fare_99         0
Age_minus       0
Fare_minus      0
Age           177
Fare            0
dtype: int64